In [1]:
import pandas as pd
import numpy as np
data = {'Name':['Dhoni','Rohit','Virat','Gill'],'Run':[12000,11000,3000,4200],'Avg':[59.5,48.7,51.2,45.3]}
df = pd.DataFrame(data,index=['A','B','C','D'])
print(df)

    Name    Run   Avg
A  Dhoni  12000  59.5
B  Rohit  11000  48.7
C  Virat   3000  51.2
D   Gill   4200  45.3

In [ ]:
print(df['Run'])

A    True
B    True
C    True
D    True
Name: Run, dtype: bool

In [3]:
print(df[['Run','Avg']])

     Run   Avg
A  12000  59.5
B  11000  48.7
C   3000  51.2
D   4200  45.3

In [11]:

print(df.shape)
print("*"*30)
print(df.index)
print("*"*30)
print(df.size)
print('*'*30)

(4, 3)
******************************
Index(['A', 'B', 'C', 'D'], dtype='object')
******************************
12
******************************

In [14]:
print(df.iloc[1:4])

    Name    Run   Avg
B  Rohit  11000  48.7
C  Virat   3000  51.2
D   Gill   4200  45.3

In [18]:
df['Run'][2] = 4000
print(df)
df.loc['C','Run'] = 5000
print(df)

    Name    Run   Avg
A  Dhoni  12000  59.5
B  Rohit  11000  48.7
C  Virat   4000  51.2
D   Gill   4200  45.3
    Name    Run   Avg
A  Dhoni  12000  59.5
B  Rohit  11000  48.7
C  Virat   5000  51.2
D   Gill   4200  45.3

C:\Users\LJENG\AppData\Local\Temp\ipykernel_5068\885363222.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Run'][2] = 4000
C:\Users\LJENG\AppData\Local\Temp\ipykernel_5068\885363222.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Run'][2] = 4000
C:\Users\LJENG\AppData\Local\Temp\ipykernel_5068\885363222.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  df['Run'][2] = 4000

In [22]:
df.set_index('Name',drop=False)

        Name    Run   Avg
Name
Dhoni  Dhoni  12000  59.5
Rohit  Rohit  11000  48.7
Virat  Virat   5000  51.2
Gill    Gill   4200  45.3

In [23]:
df.set_index(['Name','Avg'],drop=True)

              Run
Name  Avg
Dhoni 59.5  12000
Rohit 48.7  11000
Virat 51.2   5000
Gill  45.3   4200

In [25]:
data['score'] = [10000,2000,500,300]
df = pd.DataFrame(data,index=['A','B','C','D'])
print(df)

    Name    Run   Avg  score
A  Dhoni  12000  59.5  10000
B  Rohit  11000  48.7   2000
C  Virat   3000  51.2    500
D   Gill   4200  45.3    300

In [26]:
df[df['Run']>10000]

    Name    Run   Avg  score
A  Dhoni  12000  59.5  10000
B  Rohit  11000  48.7   2000

In [32]:
df[(df['Run']>1000) & (df['Avg']>50)]

    Name    Run   Avg  score
A  Dhoni  12000  59.5  10000
C  Virat   3000  51.2    500

In [33]:
df[(df['Run']>1000) & (df['Avg']>50)]['Run']

A    12000
C     3000
Name: Run, dtype: int64

In [41]:
df.sort_values(by='Avg',ascending=False,axis=0)

    Name    Run   Avg  score
A  Dhoni  12000  59.5  10000
C  Virat   3000  51.2    500
B  Rohit  11000  48.7   2000
D   Gill   4200  45.3    300

In [ ]:
df.sort_index(ascending=True,axis=1)

    Avg   Name    Run  score
A  59.5  Dhoni  12000  10000
B  48.7  Rohit  11000   2000
C  51.2  Virat   3000    500
D  45.3   Gill   4200    300

In [50]:
df.sort_values(['Run','Avg'],axis=0,ascending=[True,False])[['Run','Avg']]

     Run   Avg
C   3000  51.2
D   4200  45.3
B  11000  48.7
A  12000  59.5

In [51]:
df.sort_values(['Run','Avg'],axis=0,ascending=[True,False],ignore_index=True)[['Run','Avg']]

     Run   Avg
0   3000  51.2
1   4200  45.3
2  11000  48.7
3  12000  59.5

In [52]:
df.sort_values(['Run','Avg'],axis=0,ascending=[True,False],inplace=False)[['Run','Avg']]

     Run   Avg
C   3000  51.2
D   4200  45.3
B  11000  48.7
A  12000  59.5

In [55]:
df = pd.read_csv('./Datasets/auto-mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [56]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [57]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [63]:
df.sample(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
239,30.0,4,97.0,67,1985,16.4,77,3,subaru dl
176,19.0,6,232.0,90,3211,17.0,75,1,amc pacer
134,16.0,6,258.0,110,3632,18.0,74,1,amc matador

In [65]:
df.values

array([[18.0, 8, 307.0, ..., 70, 1, 'chevrolet chevelle malibu'],
       [15.0, 8, 350.0, ..., 70, 1, 'buick skylark 320'],
       [18.0, 8, 318.0, ..., 70, 1, 'plymouth satellite'],
       ...,
       [32.0, 4, 135.0, ..., 82, 1, 'dodge rampage'],
       [28.0, 4, 120.0, ..., 82, 1, 'ford ranger'],
       [31.0, 4, 119.0, ..., 82, 1, 'chevy s-10']],
      shape=(398, 9), dtype=object)

In [66]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [68]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [71]:
df.describe(include="all")

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [72]:
df.describe(include="object")

       horsepower    car name
count         398         398
unique         94         305
top           150  ford pinto
freq           22           6

In [73]:
df.describe(exclude='int64')

               mpg  displacement horsepower  acceleration    car name
count   398.000000    398.000000        398    398.000000         398
unique         NaN           NaN         94           NaN         305
top            NaN           NaN        150           NaN  ford pinto
freq           NaN           NaN         22           NaN           6
mean     23.514573    193.425879        NaN     15.568090         NaN
std       7.815984    104.269838        NaN      2.757689         NaN
min       9.000000     68.000000        NaN      8.000000         NaN
25%      17.500000    104.250000        NaN     13.825000         NaN
50%      23.000000    148.500000        NaN     15.500000         NaN
75%      29.000000    262.000000        NaN     17.175000         NaN
max      46.600000    455.000000        NaN     24.800000         NaN

In [78]:
df['car name'].unique

<bound method Series.unique of 0      chevrolet chevelle malibu
1              buick skylark 320
2             plymouth satellite
3                  amc rebel sst
4                    ford torino
                 ...
393              ford mustang gl
394                    vw pickup
395                dodge rampage
396                  ford ranger
397                   chevy s-10
Name: car name, Length: 398, dtype: object>

In [79]:
df.nunique()

mpg             129
cylinders         5
displacement     82
horsepower       94
weight          351
acceleration     95
model year       13
origin            3
car name        305
dtype: int64

In [82]:
df['car name'].value_counts(ascending=True)

car name
ford ranger              1
toyota corona mark ii    1
chevrolet monte carlo    1
plymouth 'cuda 340       1
dodge challenger se      1
                        ..
chevrolet chevette       4
toyota corolla           5
ford maverick            5
amc matador              5
ford pinto               6
Name: count, Length: 305, dtype: int64

In [85]:
df[df['acceleration']>20][['mpg','acceleration','model year']]

      mpg  acceleration  model year
19   26.0          20.5          70
56   26.0          20.5          71
59   23.0          23.5          72
102  26.0          21.0          73
131  32.0          21.0          74
154  15.0          21.0          75
160  17.0          21.0          75
195  29.0          22.2          76
196  24.5          22.1          76
200  18.0          21.0          76
209  19.0          21.9          76
244  43.1          21.5          78
297  25.4          20.1          79
299  27.2          24.8          79
300  23.9          22.2          79
315  24.3          20.1          80
325  44.3          21.7          80
326  43.4          23.7          80
328  30.0          21.8          80
352  29.9          20.7          81
359  28.1          20.4          81
374  23.0          20.5          82
394  44.0          24.6          82