In [1]:
import pandas as pd
import numpy as np

In [86]:
data = {'ID':[1,2,3,4],'Nmae':['Aumit','Priya','Raj','Rahul'],'Marks':[80,75,80,85],'City':['Ahmedabad','Rajkot','Bhavnagr','Surat']}
df = pd.DataFrame(data)
df

   ID   Nmae  Marks       City
0   1  Aumit     80  Ahmedabad
1   2  Priya     75     Rajkot
2   3    Raj     80   Bhavnagr
3   4  Rahul     85      Surat

In [4]:
df.isnull()

      ID   Nmae  Marks   City
0  False  False  False  False
1  False  False   True  False
2  False   True  False   True
3  False  False  False  False
4  False   True   True  False

In [6]:
df.isnull().sum()

ID       0
Nmae     2
Marks    2
City     1
dtype: int64

In [11]:
df = df.bfill()
df

   ID   Nmae  Marks       City
0   1  Aumit   80.0  Ahmedabad
1   2  Priya   75.0     Rajkot
2   3  Rahul   75.0      Surat
3   4  Rahul   85.0      Surat
4   5    NaN    NaN     Rajkot

In [13]:
df.fillna(df.mean(numeric_only=True))

   ID   Nmae  Marks       City
0   1  Aumit  80.00  Ahmedabad
1   2  Priya  75.00     Rajkot
2   3  Rahul  75.00      Surat
3   4  Rahul  85.00      Surat
4   5    NaN  78.75     Rajkot

In [14]:
df.fillna(df.median(numeric_only=True))

   ID   Nmae  Marks       City
0   1  Aumit   80.0  Ahmedabad
1   2  Priya   75.0     Rajkot
2   3  Rahul   75.0      Surat
3   4  Rahul   85.0      Surat
4   5    NaN   77.5     Rajkot

In [18]:
df.fillna(df.mode(numeric_only=True))

   ID   Nmae  Marks       City
0   1  Aumit   80.0  Ahmedabad
1   2  Priya   75.0     Rajkot
2   3  Rahul   75.0      Surat
3   4  Rahul   85.0      Surat
4   5    NaN    NaN     Rajkot

In [50]:
print(df)
df = df.fillna(df.mode().iloc[0])

df

   ID   Nmae  Marks       City
0   1  Aumit   80.0  Ahmedabad
1   2  Priya    NaN     Rajkot
2   3    NaN   80.0        NaN
3   4  Rahul   85.0      Surat
4   5    NaN    NaN     Rajkot

   ID   Nmae  Marks       City
0   1  Aumit   80.0  Ahmedabad
1   2  Priya   80.0     Rajkot
2   3  Aumit   80.0     Rajkot
3   4  Rahul   85.0      Surat
4   5  Aumit   80.0     Rajkot

In [43]:
df.fillna(method='ffill')

C:\Users\LJENG\AppData\Local\Temp\ipykernel_968\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

   ID   Nmae  Marks       City
0   1  Aumit   80.0  Ahmedabad
1   2  Priya   80.0     Rajkot
2   3  Priya   75.0     Rajkot
3   4  Rahul   85.0      Surat
4   5  Rahul   85.0     Rajkot

In [53]:
print(df)

   ID   Nmae  Marks       City
0   1  Aumit   80.0  Ahmedabad
1   2  Priya    NaN     Rajkot
2   3    NaN   80.0        NaN
3   4  Rahul   85.0      Surat
4   5    NaN    NaN     Rajkot

In [55]:
df.dropna(how='any',axis=1)

   ID
0   1
1   2
2   3
3   4
4   5

In [58]:
df.dropna(how='any')

   ID   Nmae  Marks       City
0   1  Aumit   80.0  Ahmedabad
3   4  Rahul   85.0      Surat

In [61]:
df.dropna(how='all')

    ID   Nmae  Marks       City
0  1.0  Aumit   80.0  Ahmedabad
1  2.0  Priya    NaN     Rajkot
2  3.0    NaN   80.0        NaN
3  4.0  Rahul   85.0      Surat

In [62]:
df.dropna(subset=['Marks'])

    ID   Nmae  Marks       City
0  1.0  Aumit   80.0  Ahmedabad
2  3.0    NaN   80.0        NaN
3  4.0  Rahul   85.0      Surat

In [70]:
df.dropna(thresh=0)

    ID   Nmae  Marks       City
0  1.0  Aumit   80.0  Ahmedabad
1  2.0  Priya    NaN     Rajkot
2  3.0    NaN   80.0        NaN
3  4.0  Rahul   85.0      Surat
4  NaN    NaN    NaN        NaN

In [ ]:
df.shape

(5, 4)

In [74]:
df = df.dropna()

In [75]:
df.shape

(2, 4)

In [80]:
df = df.drop(columns='City')
df

    ID   Nmae  Marks
0  1.0  Aumit   80.0
1  2.0  Priya    NaN
2  3.0    NaN   80.0
3  4.0  Rahul   85.0
4  NaN    NaN    NaN

In [82]:
df = df.drop(index=[0,2])
df

    ID   Nmae  Marks    City
1  2.0  Priya    NaN  Rajkot
3  4.0  Rahul   85.0   Surat
4  NaN    NaN    NaN     NaN

In [84]:
df = df.drop('Gender',axis=1,errors='ignore')
df

    ID   Nmae  Marks       City
0  1.0  Aumit   80.0  Ahmedabad
1  2.0  Priya    NaN     Rajkot
2  3.0    NaN   80.0        NaN
3  4.0  Rahul   85.0      Surat
4  NaN    NaN    NaN        NaN

In [87]:
data = {'ID':[1,2,3,4],'Nmae':['Aumit','Priya','Raj','Rahul'],'Marks':[80,75,80,85],'City':['Ahmedabad','Rajkot','Bhavnagr','Surat']}
df = pd.DataFrame(data)
df

   ID   Nmae  Marks       City
0   1  Aumit     80  Ahmedabad
1   2  Priya     75     Rajkot
2   3    Raj     80   Bhavnagr
3   4  Rahul     85      Surat

In [88]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [ ]:
df.duplicated(keep='first')

0    False
1    False
2    False
3    False
dtype: bool

In [91]:
df.duplicated(keep='last')

0    False
1    False
2    False
3    False
dtype: bool