In [2]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.DataFrame({'A':[1,2],'B':[3,4]})
df2 = pd.DataFrame({'A':[5,6],'B':[7,8]})

In [4]:
pd.concat([df1,df2],axis=1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [5]:
pd.concat([df1,df2])

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [6]:
df3 = pd.DataFrame({'A':[1,2],'B':[3,4]})
df4 = pd.DataFrame({'A':[5,6],'D':[7,8]})

In [7]:
pd.concat([df3,df4])

   A    B    D
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [8]:
pd.concat([df3,df4],axis=1)

   A  B  A  D
0  1  3  5  7
1  2  4  6  8

In [9]:
pd.concat([df3,df4],join='outer',ignore_index=False)

   A    B    D
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [10]:
pd.concat([df3,df4],join='inner',ignore_index=False)

   A
0  1
1  2
0  5
1  6

In [11]:
pd.concat([df3,df4],join='outer',keys=["Train",'Test'],names=['Dataset1'])

            A    B    D
Dataset1
Train    0  1  3.0  NaN
         1  2  4.0  NaN
Test     0  5  NaN  7.0
         1  6  NaN  8.0

In [12]:
df5 = pd.DataFrame({'E':[1,2],'B':[3,4]})
df6 = pd.DataFrame({'D':[5,6],'A':[7,8]})

In [13]:
pd.concat([df5,df6],sort=True)

     A    B    D    E
0  NaN  3.0  NaN  1.0
1  NaN  4.0  NaN  2.0
0  7.0  NaN  5.0  NaN
1  8.0  NaN  6.0  NaN

In [14]:
pd.concat([df5,df6],sort=False)

     E    B    D    A
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

In [15]:
employes = pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['A','B','C','D'],
    'dept_id':[10,20,10,30]
})
department = pd.DataFrame({
    'dept_id':[10,20,40],
    'name':['HR','IT','FINACE']
})
pd.merge(employes,department,on='dept_id')

   emp_id name_x  dept_id name_y
0       1      A       10     HR
1       3      C       10     HR
2       2      B       20     IT

In [16]:
pd.merge(employes,department,on='dept_id',how='inner')

   emp_id name_x  dept_id name_y
0       1      A       10     HR
1       3      C       10     HR
2       2      B       20     IT

In [17]:
pd.merge(employes,department,on='dept_id',how='outer')

   emp_id name_x  dept_id  name_y
0     1.0      A       10      HR
1     3.0      C       10      HR
2     2.0      B       20      IT
3     4.0      D       30     NaN
4     NaN    NaN       40  FINACE

In [18]:
pd.merge(employes,department,on='dept_id',how='left')

   emp_id name_x  dept_id name_y
0       1      A       10     HR
1       2      B       20     IT
2       3      C       10     HR
3       4      D       30    NaN

In [19]:
pd.merge(employes,department,on='dept_id',how='right')

   emp_id name_x  dept_id  name_y
0     1.0      A       10      HR
1     3.0      C       10      HR
2     2.0      B       20      IT
3     NaN    NaN       40  FINACE

In [20]:
pd.merge(employes,department,how='cross')

KeyError: 'cross'

In [21]:
pd.merge(employes,department,left_on='dept_id',right_on='dept_id')

   emp_id name_x  dept_id name_y
0       1      A       10     HR
1       3      C       10     HR
2       2      B       20     IT

In [22]:
pd.merge(employes,department,left_on='dept_id',right_on='dept_id',how='outer')

   emp_id name_x  dept_id  name_y
0     1.0      A       10      HR
1     3.0      C       10      HR
2     2.0      B       20      IT
3     4.0      D       30     NaN
4     NaN    NaN       40  FINACE

In [23]:
pd.merge(employes,department,left_on='dept_id',right_on='dept_id',how='outer',indicator=True)

   emp_id name_x  dept_id  name_y      _merge
0     1.0      A       10      HR        both
1     3.0      C       10      HR        both
2     2.0      B       20      IT        both
3     4.0      D       30     NaN   left_only
4     NaN    NaN       40  FINACE  right_only

In [24]:
pd.merge(employes,department,left_on='dept_id',right_on='dept_id',how='outer',indicator=True,sort=True,copy=True,suffixes=['_emp','_dpt'])

   emp_id name_emp  dept_id name_dpt      _merge
0     1.0        A       10       HR        both
1     3.0        C       10       HR        both
2     2.0        B       20       IT        both
3     4.0        D       30      NaN   left_only
4     NaN      NaN       40   FINACE  right_only

In [25]:
pd.merge(employes,department,on='dept_id',left_index=True)

   emp_id name_x  dept_id name_y
0       1      A       10     HR
0       3      C       10     HR
1       2      B       20     IT

In [31]:
employees = pd.DataFrame({'emp_id':['1','2','3','4'],
                          'name':['A','B','C','D'],
                          'Active':['y','y','y','y']})
print(employees.dtypes)

emp_id    object
name      object
Active    object
dtype: object

In [32]:
employees['emp_id'] = employees['emp_id'].astype(int)

In [33]:
print(employees.dtypes)

emp_id     int32
name      object
Active    object
dtype: object

In [34]:
employees['Active'] = employees['Active'].astype(bool)
employees

   emp_id name  Active
0       1    A    True
1       2    B    True
2       3    C    True
3       4    D    True

In [35]:
employees['name']  = employees['name'].replace('A','P')

In [36]:
employees

   emp_id name  Active
0       1    P    True
1       2    B    True
2       3    C    True
3       4    D    True