In [1]:
from bs4 import BeautifulSoup
import pandas as pd

In [16]:
webside = "Fact-checks _ PolitiFact.html"
file = open(webside,encoding='utf-8')

res = file.read()
soup = BeautifulSoup(res,"html.parser")
soup

<!DOCTYPE html>

<html dir="ltr" lang="en-US">
<head>
<meta charset="utf-8"/>
<meta content="ie=edge" http-equiv="x-ua-compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Fact-checks | PolitiFact </title>
<meta content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter." name="description">
<meta content="all" name="robots">
<meta content="PolitiFact" name="publisher"/>
<meta content="PolitiFact" name="twitter:username">
<meta content="summary" name="twitter:card">
<meta content="PolitiFact" name="twitter:site"/>
<meta content="" name="twitter:url">
<meta content="" name="twitter:title"/>
<meta content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter." name="twitter:description"/>
<meta content="vrxxsw8mwnf2pxgnwxvgsn4g93w3vm" name="facebook-domain-verification"/>
<link href="https://static.politifact.com/images/favicon.ico" rel="shortcut icon" type="image/ico"/>
<link href="https://static.politifact.com/images/favicon.png" rel="icon" type="image/png"/>
<link href="https://static.politifact.com/images/apple-touch-icon.png" rel="apple-touch-icon"/>
<link href="/rss/social/" rel="alternate" title="Latest Fact-checks and Articles" type="application/rss+xml">
<link href="/rss/factchecks/" rel="alternate" title="Latest Fact-checks" type="application/rss+xml">
<script src="https://static.politifact.com/js/sharethefacts-v1.js"></script>
<script src="//d283fm003ll1xs.cloudfront.net/script.js" type="text/javascript"></script>
<script> !(function () { window.googletag = window.googletag || {}; window.vmpbjs = window.vmpbjs || {}; window.vpb = window.vpb || {}; vpb.cmd = vpb.cmd || []; vpb.st=Date.now();  vpb.fastLoad = true; googletag.cmd = googletag.cmd || []; vmpbjs.cmd = vmpbjs.cmd || []; var cmds = []; try{ cmds = googletag.cmd.slice(0); googletag.cmd.length = 0; }catch(e){} var ready = false; function exec(cb) { return cb.call(googletag); } var overriden = false; googletag.cmd.push(function () { overriden = true; googletag.cmd.unshift = function (cb) { if (ready) { return exec(cb); } cmds.unshift(cb); if (cb._startgpt) { ready = true; for (var k = 0; k < cmds.length; k++) { exec(cmds[k]); } } }; googletag.cmd.push = function (cb) { if (ready) { return exec(cb); } cmds.push(cb); }; }); if(!overriden){ googletag.cmd.push = function (cb) { cmds.push(cb); }; googletag.cmd.unshift = function (cb) { cmds.unshift(cb); if (cb._startgpt) { ready = true; if (googletag.apiReady) { cmds.forEach(function (cb) { googletag.cmd.push(cb); }); } else { googletag.cmd = cmds; } } }; } var dayMs = 36e5, cb = parseInt(Date.now() / dayMs), vpbSrc = '//player.hbmp.ops.co/prebidlink/' + cb + '/wrapper_hb_779253_23204.js', pbSrc = vpbSrc.replace('wrapper_hb', 'hb'), gptSrc = '//securepubads.g.doubleclick.net/tag/js/gpt.js', c = document.head || document.body || document.documentElement; function loadScript(src, cb) { var s = document.createElement('script'); s.src = src; s.defer=false; c.appendChild(s); s.onload = cb; s.onerror = function(){ var fn = function(){}; fn._startgpt = true; googletag.cmd.unshift(fn); }; return s; } loadScript(pbSrc); loadScript(gptSrc); loadScript(vpbSrc); })() </script>
<script>
  window.googletag = window.googletag || {cmd: []};
  googletag.cmd.push(function() {
    const sizeMapping = googletag.sizeMapping()
        .addSize([1440, 0], [
            [970,90],
            [970,250],
            [728,90],
        ])
        .addSize([1024, 0], [
            [728,90],
            [320,100],
        ])
        .addSize([768, 0], [
            [320, 50],
            [300, 50],
        ])
        .addSize([0, 0], [
            [320, 50],
			[300, 50],
        ])
        .build();
    googletag.defineSlot('/25722649/Politifact/BottomLeaderboard_Adhesion', [[300,50],[320,50],[728,90]], 'BottomLeaderboard_Adhesion')
      .defineSizeMapping(sizeMapping)
      .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_BottomLeaderboard', [[320,50],[728,90]], 'BottomLeaderboard')
      .defineSizeMapping(sizeMapping)
      .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_MiddleRectangle', [[300,250]], 'MiddleRectangle')
             .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_TopLeaderboard', [[320,50],[728,90]], 'TopLeaderboard')
      .defineSizeMapping(sizeMapping)
      .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_TopMedRect', [[300,250],[300,600]], 'TopMedRect')
             .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/SmartNewsFeed', [[300,250]], 'SmartNewsFeed')
             .addService(googletag.pubads());

    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
  });
</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-35156640-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-35156640-2');

</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-EDXB0TJGGY"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EDXB0TJGGY');

</script>
<script async="" id="ebx" src="//applets.ebxcdn.com/ebx.js"></script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
<!-- End Facebook Pixel Code -->
<noscript><img height="1" src="//www.facebook.com/tr?id=292850974235854&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
<link href="https://static.politifact.com/assets/main-CiDydm0l.css" rel="stylesheet">
<style>
.m-notfound{padding-top:2.5rem;padding-bottom:3.5rem}@media print, screen and (min-width: 48em){.m-notfound{padding-top:5rem;padding-bottom:6rem}}.m-notfound__title{margin-bottom:2.5rem;text-align:center}@media print, screen and (min-width: 48em){.m-notfound__content{display:-webkit-box;display:-ms-flexbox;display:flex}}.m-notfound__image{margin-bottom:1.5rem;margin-left:auto;margin-right:auto;max-width:10rem}@media print, screen and (min-width: 48em){.m-notfound__image{-webkit-box-flex:0;-ms-flex:0 0 13.75rem;flex:0 0 13.75rem;max-width:none}}.m-notfound__body{padding-top:.5rem}@media print, screen and (min-width: 48em){.m-notfound__body{padding-left:2rem}}.m-notfound__body p{margin-top:0}
</style>
</link></link></link></meta></meta></meta></meta></meta></head>
<body class="" data-role="page">
<div class="global-wrapper" id="top">
<header class="o-header">
<div class="o-header__inner">
<div class="o-header__branding">
<a href="/">
<span class="m-branding">
<span class="m-branding__logo">
<svg class="c-icon">
<use xlink:href="#svg_logo-plain"></use>
</svg>
</span>
<span class="m-branding__subline">
<span class="m-branding__claim">
                  The Poynter Institute
                </span>
</span>
</span>
</a>
</div>
<div class="o-header__menu">
<a class="c-burger" data-menu-toggle="" href="#">
<span class="c-burger__lines"></span>
<span class="c-burger__value">Menu</span>
</a>
</div>
<div class="o-header__donate">
<a class="c-button c-button--small show-for-large" href="/membership/">
            Donate
          </a>
</div>
</div>
<div class="t-menu" data-menu="">
<div class="t-menu__content">
<div class="o-menu-list">
<div class="o-menu-list__inner">
<div class="o-menu-list__item">
<div aria-multiselectable="true" class="m-togglist" role="tablist">
<input class="m-togglist__checkbox show-for-sr" id="togglist_1" name="" type="checkbox" value=""/>
<label aria-controls="togglist_1" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_1" role="tab">
                    State Editions
                  </label>
<div aria-hidden="true" aria-labelledby="togglist_1" class="m-togglist__panel" role="tabpanel">
<ul class="m-togglist__list">
<li>
<a href="/california/">
                          California
                        </a>
</li>
<li>
<a href="/florida/">
                          Florida
                        </a>
</li>
<li>
<a href="/iowa/">
                          Iowa
                        </a>
</li>
<li>
<a href="/michigan/">
                          Michigan
                        </a>
</li>
<li>
<a href="/new-hampshire/">
                          New Hampshire
                        </a>
</li>
<li>
<a href="/new-york/">
                          New York
                        </a>
</li>
<li>
<a href="/north-carolina/">
                          North Carolina
                        </a>
</li>
<li>
<a href="/pennsylvania/">
                          Pennsylvania
                        </a>
</li>
<li>
<a href="/texas/">
                          Texas
                        </a>
</li>
<li>
<a href="/west-virginia/">
                          West Virginia
                        </a>
</li>
<li>
<a href="/wisconsin/">
                          Wisconsin
                        </a>
</li>
<li>
</li></ul>
</div>
</div>
</div>
<div class="o-menu-list__item">
<div aria-multiselectable="true" class="m-togglist" role="tablist">
<input class="m-togglist__checkbox show-for-sr" id="togglist_2" name="" type="checkbox" value=""/>
<label aria-controls="togglist_2" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_2" role="tab">
                    Issues
                  </label>
<div aria-hidden="true" aria-labelledby="togglist_2" class="m-togglist__panel" role="tabpanel">
<ul class="m-togglist__list">
<li>
<strong><a href="/issues/">All Issues</a></strong>
</li>
<li>
<a href="/factchecks/list/?speaker_type=SOCIAL">
                          Online hoaxes
                        </a>
</li>
<li>
<a href="/coronavirus/">
                          Coronavirus
                        </a>
</li>
<li>
<a href="/health-check/">
                          Health Care
                        </a>
</li>
<li>
<a href="/immigration/">
                          Immigration
                        </a>
</li>
<li>
<a href="https://www.politifact.com/article/2022/jun/09/political-extremism-public-square-resource-journal/">
                          Extremism
                        </a>
</li>
<li>
<a href="/taxes/">
                          Taxes
                        </a>
</li>
<li>
<a href="/marijuana/">
                          Marijuana
                        </a>
</li>
<li>
<a href="/environment/">
                          Environment
                        </a>
</li>
<li>
<a href="/crime/">
                          Crime
                        </a>
</li>
<li>
<a href="/guns/">
                          Guns
                        </a>
</li>
<li>
<a href="/foreign-policy/">
                          Foreign Policy
                        </a>
</li>
<li>
<a href="/lgbtq/">
                          LGBTQ+
                        </a>
</li>
</ul>
</div>
</div>
</div>
<div class="o-menu-list__item">
<div aria-multiselectable="true" class="m-togglist" role="tablist">
<input class="m-togglist__checkbox show-for-sr" id="togglist_3" name="" type="checkbox" value=""/>
<label aria-controls="togglist_3" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_3" role="tab">
                    People
                  </label>
<div aria-hidden="true" aria-labelledby="togglist_3" class="m-togglist__panel" role="tabpanel">
<ul class="m-togglist__list">
<li>
<a href="/personalities/donald-trump/">
                          Donald Trump
                        </a>
</li>
<li>
<a href="/personalities/jd-vance/">
                          JD Vance
                        </a>
</li>
<li>
<a href="/personalities/mitch-mcconnell/">
                          Mitch McConnell
                        </a>
</li>
<li>
<a href="/personalities/mike-johnson/">
                          Mike Johnson
                        </a>
</li>
<li>
<a href="/personalities/joe-biden/">
                          Joe Biden
                        </a>
</li>
</ul>
</div>
</div>
</div>
<div class="o-menu-list__item">
<div aria-multiselectable="true" class="m-togglist" role="tablist">
<input class="m-togglist__checkbox show-for-sr" id="togglist_4" name="" type="checkbox" value=""/>
<label aria-controls="togglist_4" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_4" role="tab">
                    Media
                  </label>
<div aria-hidden="true" aria-labelledby="togglist_4" class="m-togglist__panel" role="tabpanel">
<ul class="m-togglist__list">
<li>
<a href="/punditfact/">
                          PunditFact
                        </a>
</li>
<li>
<a href="/personalities/tucker-carlson/">
                          Tucker Carlson
                        </a>
</li>
<li>
<a href="/personalities/sean-hannity/">
                          Sean Hannity
                        </a>
</li>
<li>
<a href="/personalities/rachel-maddow/">
                          Rachel Maddow
                        </a>
</li>
<li>
<a href="/personalities/blog-posting/">
                          Bloggers
                        </a>
</li>
<li>
<a href="/videos/">
                          PolitiFact Videos
                        </a>
</li>
</ul>
</div>
</div>
<div aria-multiselectable="true" class="m-togglist" role="tablist">
<input class="m-togglist__checkbox show-for-sr" id="togglist_5" name="" type="checkbox" value=""/>
<label aria-controls="togglist_5" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_5" role="tab">
                    Campaigns
                  </label>
<div aria-hidden="true" aria-labelledby="togglist_5" class="m-togglist__panel" role="tabpanel">
<ul class="m-togglist__list">
<li>
<a href="/elections/">
                          2024 Elections
                        </a>
</li>
</ul>
</div>
</div>
</div>
<div class="o-menu-list__item">
<div aria-multiselectable="true" class="m-togglist" role="tablist">
<input class="m-togglist__checkbox show-for-sr" id="togglist_6" name="" type="checkbox" value=""/>
<label aria-controls="togglist_6" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_6" role="tab">
                    Truth-o-Meter
                  </label>
<div aria-hidden="true" aria-labelledby="togglist_6" class="m-togglist__panel" role="tabpanel">
<ul class="m-togglist__list">
<li>
<a href="/factchecks/list/?ruling=true">
                          True
                        </a>
</li>
<li>
<a href="/factchecks/list/?ruling=mostly-true">
                          Mostly True
                        </a>
</li>
<li>
<a href="/factchecks/list/?ruling=half-true">
                          Half True
                        </a>
</li>
<li>
<a href="/factchecks/list/?ruling=barely-true">
                          Mostly False
                        </a>
</li>
<li>
<a href="/factchecks/list/?ruling=false">
                          False
                        </a>
</li>
<li>
<a href="/factchecks/list/?ruling=pants-fire">
                          Pants on Fire
                        </a>
</li>
</ul>
</div>
</div>
<div aria-multiselectable="true" class="m-togglist" role="tablist">
<input class="m-togglist__checkbox show-for-sr" id="togglist_7" name="" type="checkbox" value=""/>
<label aria-controls="togglist_7" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_7" role="tab">
                    Promises
                  </label>
<div aria-hidden="true" aria-labelledby="togglist_7" class="m-togglist__panel" role="tabpanel">
<ul class="m-togglist__list">
<li>
<a href="/truth-o-meter/promises/maga-meter-tracking-donald-trumps-2024-promises/?ruling=true">
                          MAGA-Meter
                        </a>
</li>
<li>
<a href="/truth-o-meter/promises/biden-promise-tracker/?ruling=true">
                          Biden Promise Tracker
                        </a>
</li>
<li>
<a href="/truth-o-meter/promises/trumpometer/?ruling=true">
                          Trump-O-Meter
                        </a>
</li>
<li>
<a href="/truth-o-meter/promises/obameter/?ruling=true">
                          Obameter
                        </a>
<li>
<a href="/truth-o-meter/promises/list/">
                          Latest Promises
                        </a>
</li>
</li>
</ul>
</div>
</div>
</div>
<div class="o-menu-list__item">
<div aria-multiselectable="true" class="m-togglist" role="tablist">
<input class="m-togglist__checkbox show-for-sr" id="togglist_8" name="" type="checkbox" value=""/>
<label aria-controls="togglist_8" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_8" role="tab">
                    About Us
                  </label>
<div aria-hidden="true" aria-labelledby="togglist_8" class="m-togglist__panel" role="tabpanel">
<ul class="m-togglist__list">
<li>
<a href="/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/ ">
                          Our Process
                        </a>
</li>
<li>
<a href="/staff/">
                          Our Staff
                        </a>
</li>
<li>
<a href="/espanol/">
                          En Español
                        </a>
</li>
<li>
<a href="/who-pays-for-politifact/">
                          Who pays for PolitiFact?
                        </a>
</li>
<li>
<a href="/media-kit/">
                          Advertise with Us
                        </a>
</li>
<li>
<a href="/suggest/statement/">
                          Suggest a Fact-check
                        </a>
</li>
<li>
<a href="/corrections-and-updates/">
                          Corrections and Updates
                        </a>
</li>
<li>
<a href="/signup/">
                          Newsletters
                        </a>
</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="o-socializer">
<div class="o-socializer__item hide-for-large">
<a class="c-button" href="/membership/">
              Donate
            </a>
</div>
<div class="o-socializer__item o-socializer__social">
<div class="m-follow">
<h4 class="m-follow__title">
                Follow us
              </h4>
<div class="m-follow__items">
<a href="https://twitter.com/Politifact/" title="PolitiFact on Twitter">
<svg class="c-icon">
<use xlink:href="#svg_tw"></use>
</svg>
</a>
<a href="https://www.facebook.com/politifact/" title="PolitiFact on Facebook">
<svg class="c-icon">
<use xlink:href="#svg_fb"></use>
</svg>
</a>
<a href="https://bsky.app/profile/politifact.bsky.social" title="PolitiFact on Bluesky">
<svg class="c-icon">
<use xlink:href="#svg_bluesky"></use>
</svg>
</a>
</div>
</div>
</div>
<div class="o-socializer__item o-socializer__subscribe">
<div class="m-subscribe">
<div class="m-subscribe__title">
                The Facts Newsletter
              </div>
<label class="c-input">
<div class="c-input__inner">
<input class="c-input__field" name="email" placeholder="Enter your email" type="email" value=""/>
</div>
</label>
<a class="c-button c-button--hollow" href="">
                Sign up
              </a>
</div>
</div>
</div>
</div>
<div class="o-header__search">
<div class="m-search">
<form action="/search/" method="get">
<input class="m-search__checkbox show-for-sr" data-search="" id="search_form" type="checkbox"/>
<label class="m-search__toggle" for="search_form" title="Open search form">
<svg class="c-icon">
<use xlink:href="#svg_search"></use>
</svg>
</label>

In [38]:
Statement_List = soup.find_all('article',class_="m-statement")
Statement = []
User = []
Date = []
for i in Statement_List:
    User.append(i.a.text.strip())
    Statement.append(i.find("div",class_="m-statement__quote").a.text.strip())
    date = (i.find('div',class_="m-statement__desc").text.strip().split(" "))
    Date.append(date[2]+" / "+date[3].split(",")[0]+" / "+date[4])
print(Statement)
print(User)
print(Date)

['“President Trump’s tariffs are costing New York households an estimated $4,200 annually.”', '"There\'s been numerous other occasions over the years” when the federal government created a reserve similar to a new $1.776 billion anti-weaponization settlement fund.', '“San Diego mosque shooters identified as trans couple.”', 'Video shows U.S. Rep. Byron Donalds saying, “Insider trading should absolutely be allowed for members of Congress.”', 'An American passenger on the cruise ship involved in the hantavirus outbreak is a "crisis actor."', '“Florida is the only state in the nation kicking children off their affordable health coverage.”', 'In 2020, “Amy Acton called off Ohio’s election at the last minute.”', 'Imágenes muestran a personas “infectadas con Hantavirus”.', '“Today, there are more children sleeping in New York City’s homeless shelters than there are seats in Yankee Stadium.”', '“The average IRS tax refund is up 11% compared to last year.”', 'Gasoline prices have “come down very substantially today.”', 'Congress passed the 1965 Voting Rights Act because “the Democrat party at the time, especially in the South, were racially gerrymandering districts to disenfranchise Black voters.”', 'Republicans “want you to pay $1 Billion for a ballroom.”', 'Proposed data centers in New York state would use “approximately double the energy usage of all households in the state combined.”', '“California only has ‘enough’ oil and gas supply to meet demand for the next six weeks.”', '“Consumer confidence is way up."', 'From January 2025 to January 2026, “hate crimes in New York City increased by 152%”', '“Under federal law, you cannot engage in partisan gerrymandering.”', 'Imagen muestra que “950 inmigrantes derrumbaron el muro fronterizo entre México y Estados Unidos intentando ingresar a Estados Unidos” en abril 2026.', '“As a result of the \'Big Beautiful Bill\' 15 million Americans have been thrown off the healthcare that they need."', '“Secret Service remains unpaid” during the partial government shutdown.', '“Graham Platner blames Maine’s women for getting raped because he says they get f----- up drunk"', 'Video shows “unedited raw security footage” of the shooter at the April 25 White House Correspondents’ Association dinner.', '“We are right now producing more oil than Saudi Arabia and Russia combined.”', 'Since the 2020 census, Florida has "moved from a Democrat majority to a 1.5 million Republican advantage."', '“Tras el atentado a Trump”, en la cena de corresponsales de la Casa Blanca el 25 de abril, “Irán lanza un mensaje fuerte: ‘no le crean nada, miente’”.', 'U.S. Rep. Byron Donalds voted "against three pay raises for military service members, including the largest pay raise for the military in 22 years."', '"There\'s two ways of calculating percentage" decreases. “If you have a $600 drug and you reduce it to $10, that\'s a 600% reduction."', "“With one dose of ibogaine, more than 80% of people are free of (opioid) addiction. With two doses, it's more than 90%.”", "“Newly released FOIA door logs show that former President Joe Biden didn't enter the Oval Office once after the 2024 election.”"]
['Kirsten Gillibrand', 'Donald Trump', 'Social Media', 'X posts', 'X posts', 'Kathy Castor', 'Vivek Ramaswamy', 'TikTok posts', 'Christine Quinn', 'Nicholas Langworthy', 'Donald Trump', 'Byron Donalds', 'Marcy Kaptur', 'Liz Krueger', 'X posts', 'Donald Trump', 'Sam Sutton', 'Fentrice Driskell', 'Instagram posts', 'Bernie Sanders', 'Tim Scott', 'Pine Tree Results PAC', 'Social Media', 'Donald Trump', 'Ron DeSantis', 'Social Media', 'Jay Collins', 'Robert F. Kennedy Jr.', 'Joe Rogan', 'X posts']
['March / 19 / 2026', 'May / 18 / 2026', 'May / 19 / 2026', 'May / 14 / 2026', 'May / 6 / 2026', 'April / 29 / 2026', 'April / 24 / 2026', 'May / 8 / 2026', 'March / 5 / 2026', 'March / 31 / 2026', 'May / 7 / 2026', 'May / 4 / 2026', 'May / 5 / 2026', 'March / 5 / 2026', 'May / 6 / 2026', 'May / 4 / 2026', 'March / 11 / 2026', 'April / 29 / 2026', 'April / 26 / 2026', 'April / 22 / 2026', 'April / 26 / 2026', 'April / 26 / 2026', 'April / 26 / 2026', 'April / 23 / 2026', 'April / 27 / 2026', 'April / 26 / 2026', 'April / 20 / 2026', 'April / 22 / 2026', 'April / 18 / 2026', 'April / 21 / 2026']

In [39]:
dataFram = pd.DataFrame({"Sources":User,"Statement":Statement,"Date":Date})
dataFram

,Sources,Statement,Date
0,Kirsten Gillibrand,“President Trump’s tariffs are costing New Yor...,March / 19 / 2026
1,Donald Trump,"""There's been numerous other occasions over th...",May / 18 / 2026
2,Social Media,“San Diego mosque shooters identified as trans...,May / 19 / 2026
3,X posts,"Video shows U.S. Rep. Byron Donalds saying, “I...",May / 14 / 2026
4,X posts,An American passenger on the cruise ship invol...,May / 6 / 2026
5,Kathy Castor,“Florida is the only state in the nation kicki...,April / 29 / 2026
6,Vivek Ramaswamy,"In 2020, “Amy Acton called off Ohio’s election...",April / 24 / 2026
7,TikTok posts,Imágenes muestran a personas “infectadas con H...,May / 8 / 2026
8,Christine Quinn,"“Today, there are more children sleeping in Ne...",March / 5 / 2026
9,Nicholas Langworthy,“The average IRS tax refund is up 11% compared...,March / 31 / 2026
10,Donald Trump,Gasoline prices have “come down very substanti...,May / 7 / 2026
11,Byron Donalds,Congress passed the 1965 Voting Rights Act bec...,May / 4 / 2026
12,Marcy Kaptur,Republicans “want you to pay $1 Billion for a ...,May / 5 / 2026
13,Liz Krueger,Proposed data centers in New York state would ...,March / 5 / 2026
14,X posts,“California only has ‘enough’ oil and gas supp...,May / 6 / 2026
15,Donald Trump,"“Consumer confidence is way up.""",May / 4 / 2026
16,Sam Sutton,"From January 2025 to January 2026, “hate crime...",March / 11 / 2026
17,Fentrice Driskell,"“Under federal law, you cannot engage in parti...",April / 29 / 2026
18,Instagram posts,Imagen muestra que “950 inmigrantes derrumbaro...,April / 26 / 2026
19,Bernie Sanders,“As a result of the 'Big Beautiful Bill' 15 mi...,April / 22 / 2026
20,Tim Scott,“Secret Service remains unpaid” during the par...,April / 26 / 2026
21,Pine Tree Results PAC,“Graham Platner blames Maine’s women for getti...,April / 26 / 2026
22,Social Media,Video shows “unedited raw security footage” of...,April / 26 / 2026
23,Donald Trump,“We are right now producing more oil than Saud...,April / 23 / 2026
24,Ron DeSantis,"Since the 2020 census, Florida has ""moved from...",April / 27 / 2026
25,Social Media,"“Tras el atentado a Trump”, en la cena de corr...",April / 26 / 2026
26,Jay Collins,"U.S. Rep. Byron Donalds voted ""against three p...",April / 20 / 2026
27,Robert F. Kennedy Jr.,"""There's two ways of calculating percentage"" d...",April / 22 / 2026
28,Joe Rogan,"“With one dose of ibogaine, more than 80% of p...",April / 18 / 2026
29,X posts,“Newly released FOIA door logs show that forme...,April / 21 / 2026

In [15]:
dataFram.sort_values('Rating',ascending=False)

                                      Title Rating
4     Are You There God? It's Me, Margaret.    99%
6                                BlackBerry    98%
12                               Past Lives    97%
1       Spider-Man: Across the Spider-Verse    96%
19                     You Hurt My Feelings    95%
20                     John Wick: Chapter 4    94%
11                                Blue Jean    94%
18                                     Sisu    93%
29                                      Air    92%
8                                   Reality    92%
16                                Bumblebee    91%
23  Dungeons & Dragons: Honor Among Thieves    90%
27     The Angry Black Girl and Her Monster    88%
28                                  Missing    87%
15               Guy Ritchie's The Covenant    83%
10           Guardians of the Galaxy Vol. 3    82%
21                           Leave No Trace    80%
14                 Avatar: The Way of Water    76%
9                               Flamin' Hot    68%
2                        The Little Mermaid    67%
3                             The Boogeyman    63%
13              The Super Mario Bros. Movie    58%
24                             Transformers    57%
5                                    Fast X    56%
0          Transformers: Rise of the Beasts    53%
26                         A Beautiful Life    50%
22                          About My Father    36%
17                                Nefarious    33%
7                               The Machine    27%
25                                 My Fault